#!/usr/bin/perl
open(WRITE,">title.txt");
print WRITE ".title Fanout Versus Delay (TSMC)\n";
print WRITE "\n";
print WRITE ".param vdd=3.3\n";
print WRITE ".param wp=3.00e-06\n";
print WRITE ".param wn=1.20e-06\n";
print WRITE ".param vlo='0.2*vdd'\n";
print WRITE ".param vmid='0.5*vdd'\n";
print WRITE ".param vhi='0.8*vdd'\n";
print WRITE ".param opcap=0.0035p\n";
print WRITE "\n";
print WRITE "vdd vdd vss vdd\n";
print WRITE "vss vss 0   0\n";
print WRITE "vin n2 vss pwl(  0   0 \n";
print WRITE "+               10p  0\n";
print WRITE "+              110p  5\n";
print WRITE "+             50.11n 5\n";
print WRITE "+             50.21n 0\n";
print WRITE "+ )\n";
print WRITE "\n";
print WRITE "* 5V Vdd\n";
print WRITE "* DC:  3.122/1.2  2.6 /1.0  1.838/0.6  1.76/0.58  0.732/0.3  # Centered DC Vthres\n";
print WRITE "* AC:  3.01 /1.2  2.61/1.0  1.783/0.6  1.70/0.58  0.694/0.3  # Balanced Rise/Fall Delays @ FO=16 705ps\n";
print WRITE "* AC:  3.25 /1.2  2.76/1.0  1.740/0.6             0.800/0.3  # Balanced Rise/Fall Slews  @ FO=16\n";
print WRITE "* HSP: 3.06 /1.2\n";
print WRITE "\n";
print WRITE "* 3.3V Vdd\n";
print WRITE "* AC:  3.56/1.2  3.20/1.0  2.52/0.6 0.75/0.3  # Balanced Rise/Fall Delays @ FO=16 705ps 1.04ns\n";
print WRITE "\n";
print WRITE ".MODEL nd NMOS\n";
print WRITE ".MODEL pd PMOS\n";
print WRITE "\n";
print WRITE ".subckt inv (outn in vdd vss)\n";
print WRITE "m1 vdd in outn vdd pd l=5e-07 w=wp\n";
print WRITE "m2 vss in outn vss nd l=5e-07 w=wn\n";
print WRITE ".ends inv\n";
print WRITE "\n";
print WRITE "xinv3 n3 n2 vdd vss inv\n";
print WRITE "C1 n3 0 opcap \n"; 
print WRITE "\n";
print WRITE ".temp 85\n";
print WRITE ".tran 1p 110n\n";
print WRITE "\n";
print WRITE ".meas tran n2_first_fall when v(n2)=vmid fall=1\n";
print WRITE "\n";
print WRITE ".meas tran n3_first_rise when v(n3)=vmid rise=1\n";
print WRITE "\n";
print WRITE ".meas tran drise trig v(n2) val=vmid fall=1\n";
print WRITE "+                targ v(n3) val=vmid rise=1\n";
print WRITE "\n";
print WRITE ".meas tran dfall trig v(n2) val=vmid rise=1\n";
print WRITE "+                targ v(n3) val=vmid fall=1\n";
print WRITE "\n";
print WRITE ".meas tran slewr trig v(n3) val=vlo rise=1\n";
print WRITE "+                targ v(n3) val=vhi rise=1\n";
print WRITE "\n";
print WRITE ".meas tran slewf trig v(n3) val=vhi fall=1\n";
print WRITE "+                targ v(n3) val=vlo fall=1\n";
print WRITE "\n";
print WRITE ".end\n";
