#!/usr/bin/perl -w
use strict;
use vars qw($mw $sp);
use Tk;


BEGIN{
    require Tk::Splashscreen;
    use Tk;
    
    $mw = MainWindow->new(-title=>'text');
    
    $sp = $mw->Splashscreen();
    
    $sp->Label(
         -text   => 'Starting up',
         -width  => 20,
         -height => 10,
         -font => [-size => 50]
    )->pack();
    
    $sp->Splash(5000); # init splash screen
    
    $sp->update;  # and display it
    
    #$mw->withdraw; # hide main widow during init

    for my $x(0..20) # junk
    {
       for my $y (0..20)
       {
           $mw->Label(
               -text => "$x:$y",
           )->grid(
               -row => $x,
               -column => $y
           );
       }
     }
     sleep 3; # and a little wait if desired
     
    $sp->Destroy(); # get rid of Splash
    
    $mw->deiconify; # and show main window
}

MainLoop;
