#!/bin/local/perl -w


%resistor ={
     net1 = 2,
     net2 = 2,
     net3 = 2,
     net4 = 2,
     net5 = 2,
     net6 = 2,
     net7 = 2,
     net8 = 2,
     net9 = 2,
     net10 = 2,
     net11 = 2,
     net12 = 2,
           }


