#!/bin/perl 

package eFarmDB;

## explanation of the object entries
## MAC : array of machines
## T : type of machine  1-master, 0-slave etc

sub new {
my $inst = {
                    MAC => [],
                    T => 0,
                    };
bless $inst, 'eFarmDB';
return $inst;
}#sub new


#---------------------------------#
sub dbeFarmAddMachine {
my ($self, $mac) = @_;
push(@{$self->{MAC}}, $mac );
}#sub dbeFarmAddMachine

sub dbeFarmGetMachine {
my ($self) = @_;
my @macs = @{$self->{MAC}};
return(@macs);
}#sub dbeFarmGetMachine

#---------------------------------#
sub dbeFarmSetMachineType {
my ($self, $type) = @_;
$self->{T} = $type;
}#sub dbeFarmSetMachineType

sub dbeFarmGetMachineType {
my ($self) = @_;
my $type = $self->{T};
return($type);
}#sub dbeFarmGetMachineType

#---------------------------------#

#---------------------------------#

1,
