#!/usr/bin/perl
my $num = $ARGV[0];
my $width = $ARGV[1];
sub dec2bin { 
    my $str = unpack("B32", pack("N", shift)); 
    $str =~ s/^0+(?=\d)//;
    my @digits = split(//,$str);
    my $len_str = @digits;
    my $len_diff = $width - $len_str;
    for(my $i=0; $i<$len_diff; $i++){
       $str = "0".$str;
    }
    return $str;
}#sub dec2bin

my $bin_value = &dec2bin($num);

print "binary value is: $bin_value\n";


