#!/usr/bin/perl      
use Tk;
     use Tk::LineGraph;
     use Tk::LineGraphDataset;

     my $mw = MainWindow->new;

     my $cp = $mw->LineGraph(-width=>500, -height=>500, -background => "snow", -scale=> [0,20,0.5])->grid;

     my @y1Array = (1..5,18..25,30,31,32,33);
     my @y2Array = (6..10,11..18,0,0,0,0);
  #my @Arr = ([1..5,18..25,30,31,32,33],[6..10,11..18,0,0,0,0]);
     my @xArray = (7..11,20..27,28,29,30,31);
for ($i=0;$i<=17;$i++){
if ($i==0){@yArray=@y1Array;}
if ($i==0){@yArray=@y2Array;}; 
     my $ds = LineGraphDataset->new(-yData=>\@yArray,-xData=>\@xArray, -name=>'1');
     #my $ds1 = LineGraphDataset->new(-yData=>\@y2Array,-xData=>\@xArray, -name=>'1');
#     $ds2 = $cp->addDatasets( -dataset => $ds, -dataset => $ds1 );
#     my $ds3 = LineGraphDataset->new(-yData=>\@y2Array, );
     $cp->plot(-dataset=>$ds );
}

     MainLoop;

