#!/usr/bin/perl
use Benchmark;
my $t0 = new Benchmark;
my $noOfArg = @ARGV; 
if($ARGV[0] eq "-h" || $ARGV[0] eq "-help" || $ARGV[0] eq "-HELP"){
   print"Usage: populateSlvrnDBDef -lef <lef file>\n";
   print"                  -def <def file>\n";
   print"                  -output <output file>\n";
}else{
  my $lef_file = "";
  my $def_file = "";
  my $output = "";
  my $verilog_file = "";
  my $cloud_share_path;
  for(my $xx=0; $xx<$noOfArg; $xx++){
    if($ARGV[$xx] eq "-lef"){$lef_file = $ARGV[$xx+1];$xx++;}
    elsif($ARGV[$xx] eq "-def"){$def_file = $ARGV[$xx+1];$xx++;}
    elsif($ARGV[$xx] eq "-output"){$output = $ARGV[$xx+1];$xx++;}
    elsif($ARGV[$xx] eq "-cloud_share_path"){$cloud_share_path = $ARGV[$xx+1];$xx++;}
    else {push(@argList,$ARGV[$xx])};
  }#for
   my $argLine = join " ", @argList;
   open(WRITE,">script");
   print WRITE "read_lef -lef $lef_file -tech also\n";
   print WRITE "read_def -def $def_file --all\n";
   print WRITE "write_sdef -output $output $argLine\n"; 
   print WRITE "exit\n";
   close(WRITE);
   system("/home/mansis/Projects/proton/proton -f script --nolog");
   #system("$cloud_share_path/apps/content/drupal_app/proton -f script --nolog");

}#else
my $t1 = new Benchmark;
my $td = timediff($t1, $t0);
print "populateSlvrnDBDef took:",timestr($td),"\n";

