#!/usr/bin/perl -w
my $inputFile = $ARGV[0];
my $outputFile = $ARGV[1];

open(READ,"<$inputFile");
open(WRITE,">$outputFile");

while(<READ>){
chomp;
 s/\/\*.*//g;
 s/\(\*.*//g;
 print WRITE "$_\n";
}

close(WRITE);
close(READ);


